version: '3.0'

services:

  reverse-proxy:
    image: jwilder/nginx-proxy
    container_name: "reverse-proxy"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
  
networks:
  proxy:
    external: true
