<?php

include("config.php");
$db_link = mysqli_connect($db["host"], $db["user"], $db["pass"]);
mysqli_select_db($db["name"], $db_link);

mysqli_query("DELETE FROM `news`");
mysqli_query("DELETE FROM `users`");
mysqli_query("DELETE FROM `comments`");

//mysqli_query("CREATE TABLE `news` (`id` INT NOT NULL AUTO_INCREMENT,`small_text` TEXT NULL,`full_text` TEXT NULL, PRIMARY KEY (`id`))");
//mysqli_query("CREATE TABLE `comments` (`id` INT NOT NULL AUTO_INCREMENT,`news_id` INT NULL,`comment` TEXT NULL,`name` TEXT NULL, PRIMARY KEY (`id`))");
//mysqli_query("CREATE TABLE  `users` (`id` INT NOT NULL AUTO_INCREMENT,`login` TEXT NOT NULL,`password` TEXT NOT NULL, PRIMARY KEY (`id`)););");

mysqli_query("INSERT INTO `users` (`id`, `login`, `password`) VALUES (1, 'user01','P@ssw0rd'),(2, 'user02','P@ssw0rd'),(3, 'user03','P@ssw0rd'),(4, 'user04','P@ssw0rd'),(5, 'user05','P@ssw0rd'),(6, 'user06','P@ssw0rd'),(7, 'user07','P@ssw0rd'),(8, 'user08','P@ssw0rd'),(9, 'user09','P@ssw0rd'),(10, 'user10','P@ssw0rd'),(11, 'user11','P@ssw0rd'),(12, 'user12','P@ssw0rd'),(13, 'user13','P@ssw0rd'),(14, 'user14','P@ssw0rd'),(15, 'user15','P@ssw0rd'),(16, 'admin', 'qwerty');");

mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('1', 'NASA TV to Broadcast Hispanic Heritage Event', 'Oct. 10, 2017 - NASA will celebrate Hispanic Heritage Month at the James Webb Auditorium in the agency\'s headquarters in Washington on Thursday, Oct. 12, with a discussion of the contributions of Hispanics to NASA\'s mission and the importance of Hispanic representation in science, technology, engineering and mathematics (STEM) education and careers.','user01');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('2', 'NASA to Televise International Space Station Cargo Ship Launch', 'Oct. 10, 2017 - NASA Television will provide live coverage of the launch and docking of a Russian cargo spacecraft delivering almost three tons of food, fuel and supplies to the International Space Station beginning at 5:15 a.m. EDT Thursday, Oct. 12.','user02');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('3', 'Media Accreditation Opens for Launch of NOAA\'s JPSS-1 Satellite', 'Oct. 6, 2017 - The Joint Polar Satellite System-1 (JPSS-1), the first in a new series of four highly advanced National Oceanic and Atmospheric Administration (NOAA) polar-orbiting satellites, which will help increase weather forecast accuracy from three to seven days out, is scheduled to launch on Friday, Nov. 10 from Vandenberg Air Force Base, California.','user03');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('4', 'NASA Offers Access to Cygnus Spacecraft Ahead of Next Space Station Mi', 'Oct. 6, 2017 - Media are invited to view and photograph Orbital ATK\'s Cygnus spacecraft, packed with cargo and scientific experiments for its upcoming flight to the International Space Station, at 10:30 a.m. EDT Wednesday, Oct. 18, at NASA\'s Wallops Flight Facility on Wallops Island, Virginia.','user04');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('5', 'NASA Statement on National Space Council Policy', 'Oct. 5, 2017 - The following is a statement from acting NASA Administrator Robert Lightfoot about the results from the first meeting of the National Space Council on Thursday:','user05');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('6', 'Michigan Students to Speak with NASA Astronauts on Space Station', 'Oct. 5, 2017 - Students at St. Mary Cathedral School in Gaylord, Michigan, will speak with NASA astronauts living, working and doing research aboard the International Space Station at 11 a.m. EDT Friday, Oct. 6.','user06');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('7', 'NASA Provides Coverage for First Meeting of the National Space Council', 'Oct. 4, 2017 - NASA Television and the agency\'s website will provide live coverage of the first meeting of the National Space Council starting at 10 a.m. EDT Thursday, Oct. 5.','user07');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('8', 'Next International Space Station Crew Available for News Conference', 'Oct. 3, 2017 - NASA astronaut Scott Tingle and crewmates Anton Shkaplerov of the Russian space agency Roscosmos and Norishige Kanai of the Japan Aerospace Exploration Agency (JAXA) will discuss their upcoming mission to the International Space Station in a news conference at 2 p.m. EDT on Wednesday, Oct. 11 at NASA\'s Johnson Space Center in Houston.','user08');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('9', 'NASA Invites Media to \'Rocket Day\' for Space Launch System', 'Sept. 29, 2017 - Media are invited to learn about NASA\'s deep space exploration plans and view hardware for the world\'s most powerful rocket, NASA\'s Space Launch System (SLS), at the agency\'s Rocket Day, Wednesday, Oct. 11, at NASA locations in Mississippi and Louisiana.','user09');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('10', 'NASA Opens Media Accreditation for November Space Station Cargo', 'Sept. 29, 2017 - Media accreditation is open for the launch of the eighth Orbital ATK cargo resupply flight to the International Space Station from NASA\'s Wallops Flight Facility in Virginia.','user10');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('11', 'South Carolina Students to Speak with NASA Astronaut on Space Station', 'Sept. 28, 2017 - Students at Laing Middle School in Mount Pleasant, South Carolina, near Charleston, will speak with a NASA astronaut living, working and doing research aboard the International Space Station at 11:30 a.m. EDT Monday, Oct. 2.','user11');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('12', 'Briefing, NASA Television Coverage Set for Upcoming US Spacewalks', 'Sept. 28, 2017 - Three American astronauts aboard the International Space Station will embark on a trio of spacewalks in October to perform station maintenance. NASA Television and the agency\'s website will provide live coverage of the spacewalks, as well as a briefing to discuss the work to be performed.','user12');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('13', 'Vice President Pence Visits NASA\'s Marshall Space Flight Center', 'Sept. 26, 2017 - Vice President Mike Pence offered his thanks Monday to employees working on NASA\'s human spaceflight programs during a tour of the agency\'s Marshall Space Flight Center in Huntsville, Alabama.','user13');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('14', 'Vice President Pence to Visit NASA\'s Marshall Space Flight Center', 'Sept. 24, 2017 - Vice President Mike Pence will visit NASA\'s Marshall Space Flight Center in Huntsville, Alabama, on Monday, Sept. 25.','user14');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('15', 'Students at National Air and Space Museum to Speak with NASA Astronaut', 'Sept. 21, 2017 - Students at the Smithsonian\'s National Air and Space Museum in Washington will speak with a NASA astronaut living, working and doing research aboard the International Space Station at 12:25 a.m. EDT Wednesday, Sept. 27, as part of a “STEM in 30” broadcast.','user15');");
mysqli_query("INSERT INTO `news` (`id`, `small_text`, `full_text`,`author`) VALUES ('16', 'Media Invited to View NASA Spacecraft That Will Touch Our Sun', 'Sept. 20, 2017 - NASA\'s Parker Solar Probe will be humanity\'s first-ever mission to explore the Sun\'s outer atmosphere. Media are invited to see the spacecraft and learn about the mission from noon to 2 p.m. EDT Monday, Sept. 25, at Johns Hopkins University Applied Physics Laboratory (APL) in Laurel, Maryland, where the probe is being built.','admin');");
?>